### PR TITLE
Better integration with RStudio spellchecking

### PR DESCRIPTION
**Pull request by GegznaV**
I implemented some ideas, that help to have better integration with native RStudio spellchecking functionality: add-in tries to use and (to set) spellchecking default language, used by RStudio.
Check, if you like these improvements and if they work on Linux.

### CODE REVIEW

**Comment by nevrome** [comment]
A good idea and it works fine. Four comments: 

1. I don't know if we have to export the functions and their documentation. Is it necessary for the user to use these functions directly? And if so: Maybe we could add the documentation of these functions to `@rdname wellspell` or at least document them in one Rd file as they are pretty similar. I wanted to keep the documentation of this package as slim as somehow possible.

2. The source NAMESPACE of `.rs.readUiPref()` and `.rs.writeUiPref()` is missing.

3. The documentation has to be rendered before merging.

4. If we change the Rstudio language settings we should at least inform the user with a message.

**Comment by GegznaV** [comment]
1. Point 1: It is not necessary to export neither function nor documentation. We can use them for internal purposes only. I removed `@export` and added `@keywords internal`.
(Off-topic: my personal preference is to create separate documentation files for each function and link the functions in section `@seealso`, if needed.)
2. Point 2: these functions come with RStudio and I'm not sure, how to `@import` them.  
The functions are taken from `"tools:rstudio"` which is on `search()` path if RStudio is used (and this is an RStudio add-in, by the way). Analogous functions in **rstudioapi** package do not work on my PC. And I used `exists()` to check if the functions are present. We can additionally use `utils::globalVariables(c(".rs.readUiPref", ".rs.writeUiPref"))` to prevent notes while checking the package. Would it be enough?
3. Point 3 was fixed:  Rd files were created.
4. Point 4 was fixed: message created. Is this implemented as you expected?

**Comment by nevrome** [comment]
Excellent job!

1. I recently learned from the rOpenSci review process that you should also use the `@noRd` tag for internal functions.
2.  Hm... That's a tough one. It feels like accessing the RStudio API in an unsafe way. I believe we could do it like you suggested for now. You could add `utils::globalVariables(c(".rs.readUiPref", ".rs.writeUiPref"))` in a new file `zzz.R`. But maybe we open an issue to keep this problem in mind? In six months we could test the rstudioapi functions again. Would be ok for me. 
3. :+1: 
4. :+1:

**Comment by nevrome** [comment]
Off topic: Did you see [this](https://github.com/rstudio/rstudio/issues/2825)? Online spellchecking is now part of the Rstudio daily builds. I guess we will have to focus on the Languagetool features to stay relevant.

**Comment by GegznaV** [comment]
1. `@noRd` added.
2. In the current development version of RStudio 1.3, there are new ways to access user interface preferences: this functionality was redesigned (rstudio/rstudio#5262). The development version of **rstudioapi** has new appropriate functions (rstudio/rstudioapi#150). Unfortunately, the current stable version of RStudio is 1.2 and it does not have this functionality.
I agree, that a new issue that reminds us that some functionality should be updated is necessary.

**Comment by GegznaV** [comment]
> Off topic: Did you see this? Online spellchecking is now part of the Rstudio daily builds.

I know about this functionality. But, as I know, if checks spelling just in some kinds of documents. And **wellspell.addin** can do this in any selected area of any kind of file/document so it is really handy. And I find the add-in as a complement to current functionality suggested by RStudio. Because of this, I suggested this pull request.

**Comment by nevrome** [comment]
Ja - it's still useful. https://twitter.com/nevromeCS/status/1168265734650302465?s=20

**Pull request merged**
